name: CD
on:
  push:
    branches:
      - master
      - alpha

jobs:
  build:
    name: Build, test, and publish
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - uses: bahmutov/npm-install@v1

      - name: Build
        run: yarn build

      - name: UI tests
        run: |
          yarn snowpack dev & yarn wait-on http://localhost:8080/examples/popup
          yarn percy exec -- cypress run -e CI=true
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}

      - name: Deploy to NPM
        run: yarn semantic-release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN_SEMANTIC_RELEASE }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
